# Generated by Django 4.0.5 on 2022-06-05 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduquestapi', '0002_answercomment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', to='eduquestapi.answer'),
        ),
    ]
