# Generated by Django 4.0.5 on 2022-06-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduquestapi', '0003_alter_answercomment_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answercomment',
            old_name='commenter',
            new_name='author',
        ),
    ]
